apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
namespace: flux-system

# patch all deployments resources limits to be 0.5 CPU, 256MB memory
patches:
- target:
    kind: Deployment
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/resources/limits
      value:
        cpu: 500m
        memory: 256Mi
