apiVersion: apps/v1
kind: Deployment
metadata:
  name: pictrs
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: pictrs
        image: pictrs
        env:
        - name: PICTRS__SERVER__API_KEY
          valueFrom:
            secretKeyRef:
              name: lemmy
              key: pictrs-api-key
        - name: PICTRS__TRACING__LOGGING__TARGETS
          value: debug
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      securityContext:
        runAsUser: 991
        runAsGroup: 991
        fsGroup: 991
---
apiVersion: v1
kind: Service
metadata:
  name: pictrs
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  type: ClusterIP
